apiVersion: apps/v1              # Kubernetes API version 
kind: Deployment                 # Kind of kubernetes resource (Deployment)
metadata:                        # Metadata about the resource
  name: [deployment-name]
  labels:
    app: [deployment-label]
spec:
  replicas: 1                    # Number of pods to create 
  selector:                      # The selector is used to select the pod template (based on labels) 
    matchLabels:
      app: [pod-label]
  template:                      # Pod template (Note the selector matches the template label)           
    metadata:
      labels:
        app: [pod-label]
    spec:
      containers:                # Containers that will run in the pod
      - name: [container-name]    
        image: [container-image]
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /heath/live
            port: 80
          initialDelaySeconds: 15 # Wait 15 seconds before sending first probe
          timeoutSeconds: 2 # Timeout request after 2 seconds (Default is 1)
          periodSeconds: 5 # Check every 5 seconds (Default is 10)
          failureThreshold: 1 # Allow 1 failure before failing pod (Default is 3)
        readinessProbe:
          httpGet:
            path: /heath/live
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5 # Default is 10
          failureThreshold: 1 # Default is 3