apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: host-rule-ingress
spec:
  rules:
  - host: [host-Name]
    http:
      paths:
      - backend:
          serviceName: [service-Name]
          servicePort: [service-Port]