apiVersion: v1                      # Kubernetes API version 
kind: Pod                           # Kind of kubernetes resource (Pod)
metadata:                           # Metadata about the resource
  name: [pod-name]
  labels:
    app: [pod-label]
spec:                               # Specifications for the resource 
  containers:                       # Information about the containers that wll run in the pod 
  - name: [container-name]
    image: [container-image]
    ports:
    - containerPort: 80
  
# kubectl apply –f pod.yaml      
# kubectl describe pod [pod-name]
# kubectl edit -f pod.yaml
# Kubectl delete –f pod.yaml

# To exec into container use:
# kubectl exec pod-name -it sh